server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password:
  application:
    name: order-service

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
