server:
  port: 9001
  
spring:
  application:
    name: user-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/userdb
    password: aman
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

