server:
  port:9001
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/userdb
    password: aman
  application:
    name: user-service-prod
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

